### ISSUE TITLE
能否交流一下 loss 曲线的截图？

### ISSUE THREAD

**Issue by Sanster** [WenmuZhou/PSENet.pytorch#1]
hi，我自己也实现了一遍 pse net 的 loss 部分，输入相同的 tensor 和你的 loss 输出是一样的，但是我训起来曲线很怪（如图），方便贴下你的 loss 图吗？谢谢
![image](https://user-images.githubusercontent.com/3998421/55289481-e8404900-53f9-11e9-83db-88f80a76e6de.png)

**Comment by WenmuZhou** [comment]
我的loss是这样的
![BP{N28H118AB40PFDP7 T9P](https://user-images.githubusercontent.com/12406017/55326977-a24bb980-54bb-11e9-872d-120f627f26da.png)

**Comment by xiiiiiiii** [comment]
> 我的loss是这样的
> ![BP{N28H118AB40PFDP7 T9P](https://user-images.githubusercontent.com/12406017/55326977-a24bb980-54bb-11e9-872d-120f627f26da.png)

这个loss就是这个样子的吗？为什么感觉好奇怪，是上下波动的锯齿状吗？

**Comment by WenmuZhou** [comment]
按照batch来训练，波动是很正常的按照batch来训练，波动是很正常的
