### ISSUE TITLE
eval.py的问题

### ISSUE THREAD

**Issue by xiiiiiiii** [WenmuZhou/PSENet.pytorch#10]
我在改了路径之后，运行eval.py
出现了这个问题：
![image](https://user-images.githubusercontent.com/45999214/59506068-e30f7800-8ed9-11e9-82c2-c7901117e418.png)
我运行环境是windows10，torch1.1.0，torchvision0.3.0
想问问这个是什么原因呢？

**Comment by WenmuZhou** [comment]
这个pse.so是必须要在linux下面编译的，win下面可以用py的pse

**Comment by xiiiiiiii** [comment]
> 这个pse.so是必须要在linux下面编译的，win下面可以用py的pse

感谢哈哈哈，我一路在这里自问自答，果然还是得认真分析了之后在来提问哈哈哈
