### ISSUE TITLE
问一下博主运行的环境是python3.6吗？有关编译有关问题

### ISSUE THREAD

**Issue by xiiiiiiii** [WenmuZhou/PSENet.pytorch#11]
![image](https://user-images.githubusercontent.com/45999214/59558627-fbda7380-9028-11e9-8bac-509ce5ba71bb.png)
我用的python3.6 torch1.1.0 vision0.3.0 ubuntu系统，为什么会出现这个错误呢？博主是ubuntu还是windows呢？

**Comment by xiiiiiiii** [comment]
解决了，自己给自己回答一下，参考[https://blog.csdn.net/ab0902cd/article/details/88352417](url)

**Comment by xiiiiiiii** [comment]
怕是某天博主想起来，然后看了一下issue,怕是觉得这个人有病233333当自己家的聊天框了吗？是的，没错

**Comment by Crescentz** [comment]
thx
