### ISSUE TITLE
Traning on tianchi data

### ISSUE THREAD

**Issue by NormalAppler** [WenmuZhou/PSENet.pytorch#2]
Hi,When I use the code to train TianChi Data,It doesn't work.Many errors happened.So have you trained on TianChi Data?Which code should I modify  to train TianChi data.Could you give me some advice ? Thank you

**Comment by WenmuZhou** [comment]
能给个链接吗，天池的数据

**Comment by NormalAppler** [comment]
链接：https://pan.baidu.com/s/11kM4yC_qOrQabNjM6d04rQ 提取码：ue1p 
这是天池数据 9000张训练，1000张测试

**Comment by WenmuZhou** [comment]
你需要改一下这里 https://github.com/WenmuZhou/PSENet.pytorch/blob/6c435d95f71c6022ba1a97ef1c9b371b8b960132/dataset/data_utils.py#L164-L165

**Comment by NormalAppler** [comment]
> 你需要改一下这里
> 
> [PSENet.pytorch/dataset/data_utils.py](https://github.com/WenmuZhou/PSENet.pytorch/blob/6c435d95f71c6022ba1a97ef1c9b371b8b960132/dataset/data_utils.py#L164-L165)
> 
> Lines 164 to 165 in [6c435d9](/WenmuZhou/PSENet.pytorch/commit/6c435d95f71c6022ba1a97ef1c9b371b8b960132)
> 
>  d = pathlib.Path(x) 
>  label_path = os.path.join(data_dir, 'gt', ('gt_' + str(d.stem) + '.txt'))

这个地方改了，而且还改了那个判断数据格式正则表达式的地方，依然报错，训练的时候没事，就是在进行对测试集进行验证的时候，进度条结束以后就会报错

**Comment by WenmuZhou** [comment]
你验证的gt换了吗，我用的验证的脚本是icdar2015的，你可能要根据天池的做一下修改

**Comment by NormalAppler** [comment]
我再查看一下，谢谢

**Comment by NormalAppler** [comment]
作者，你好，发现天池的数据集txt文件中的坐标是逆时针的，而IDCAR的数据是顺时针的，请问再训练的时候有影响吗，需要换成顺时针的吗

**Comment by WenmuZhou** [comment]
没有试过这样的数据，不可以训练一下，看会不会报错

**Comment by NormalAppler** [comment]
好的，谢谢

**Comment by xiiiiiiii** [comment]
> 作者，你好，发现天池的数据集txt文件中的坐标是逆时针的，而IDCAR的数据是顺时针的，请问再训练的时候有影响吗，需要换成顺时针的吗

需要对逆时针的数据进行判断，改成顺时针的
