### ISSUE TITLE
再训练

### ISSUE THREAD

**Issue by Crescentz** [WenmuZhou/PSENet.pytorch#23]
是不是只可以再resnet上进行训练，不能在自己已经训练好的模型上，再进行训练

**Comment by WenmuZhou** [comment]
可以啊，https://github.com/WenmuZhou/PSENet.pytorch/blob/master/config.py#L29-L31 改这三行，pretrained=False,restart_training =False,checkpoint =model_path

**Comment by Crescentz** [comment]
Duplicate of #22

**Comment by Crescentz** [comment]
![image](https://user-images.githubusercontent.com/35165563/62441969-d34d3b00-b788-11e9-8a5e-ec84da84638e.png)

问题指向了torch.optim.lr这个函数，应该是没有找到指定的学习率，
![image](https://user-images.githubusercontent.com/35165563/62441982-da744900-b788-11e9-8ddf-2c6af6af3dac.png)


注意到你在utlis里的lr_cheduler写了继承类，但是再debug时候还会跳转到torch里的optim，目前我还不知道该咋处理。。。

**Comment by Crescentz** [comment]
Traceback (most recent call last):
  File "train.py", line 244, in <module>
    main()
  File "train.py", line 194, in main
    last_epoch=start_epoch)
  File "/home1/zy/miniconda3/envs/str/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 192, in __init__
    super(MultiStepLR, self).__init__(optimizer, last_epoch)
  File "/home1/zy/miniconda3/envs/str/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 24, in __init__
    "in param_groups[{}] when resuming an optimizer".format(i))
KeyError: "param 'initial_lr' is not specified in param_groups[0] when resuming an optimizer"

**Comment by Crescentz** [comment]
```
    if config.checkpoint != '' and not config.restart_training:
 
        start_epoch = load_checkpoint(config.checkpoint, model, logger, device)
        start_epoch += 1
        scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, config.lr_decay_step, gamma=config.lr_gamma,
                                                      last_epoch=start_epoch)
```

修改你说的这三项，是跳到这里，应该是断点继续训练

**Comment by WenmuZhou** [comment]
utils里的lr_cheduler是没用的

**Comment by wdsd641417025** [comment]
请问这个问题是怎么解决的
