### ISSUE TITLE
程序吐核

### ISSUE THREAD

**Issue by xuweidongkobe** [WenmuZhou/PSENet.pytorch#24]
老哥，不管是用gpu还是cpu，运行predict.py每次都是吐核，很无语，你遇到过吗？

**Comment by Crescentz** [comment]
吐核是啥意思啊

**Comment by xuweidongkobe** [comment]
@Crescentz 
代码运行后，linux系统返回：段错误（吐核）

**Comment by WenmuZhou** [comment]
centos吗，我用centos遇到了这个问题，换成ubuntu就好了

**Comment by xuweidongkobe** [comment]
@WenmuZhou 对的，明天打个ubuntu的docker试试。老哥，知道centos下吐核是什么原因吗？

**Comment by WenmuZhou** [comment]
不知道啊，应该是pse.cpp那一块的问题

**Comment by xuweidongkobe** [comment]
@WenmuZhou 好的。老哥，你写的基于mobilenetv3的psenet可以直接训练成功吧？

**Comment by WenmuZhou** [comment]
可以，但是我之前测的那个效果不太行

**Comment by xuweidongkobe** [comment]
@好吧。模型能提供出来，我迁移训练到我的场景试一下吗？

**Comment by WenmuZhou** [comment]
可以的

**Comment by xuweidongkobe** [comment]
@WenmuZhou 能麻烦老哥加一下wx吗？18896726312

**Comment by WenmuZhou** [comment]
加过啊，我是文幕
