### ISSUE TITLE
大神，感觉效果没有提升呀，求指点一二

### ISSUE THREAD

**Issue by ztoString** [WenmuZhou/PSENet.pytorch#29]
现在训练了50轮了，貌似在验证集上的分数只有0.64左右，感觉最后最多到0.65就算到头了/(ㄒoㄒ)/~~
我是在mtwi数据集上跑的，直接restart_training的，是不是应该在你的resnet-50上边接着训练会好一点，或者把ICDAR和MLT的数据集也加入进去一起训练，求前辈指点迷津~

**Comment by WenmuZhou** [comment]
继续训练

**Comment by Whu-wxy** [comment]
我这两天用ICDAR2015训练了70k，验证集上的分数只有0.64左右，是正常的吗 @WenmuZhou

**Comment by WenmuZhou** [comment]
不正常呀
