### ISSUE TITLE
Training to suspend

### ISSUE THREAD

**Issue by xbpgithub** [WenmuZhou/PSENet.pytorch#3]
作者你好，我在ICDAR2015数据集上尝试训练的时候，训练过程中使用测试集进行测试完保存模型后，程序会中止在那。既不继续训练，也不报错。
我尝试在保存完模型再重新加载模型，还是不能继续训练，也不报错。
我对pytorch不是很熟，不知道什么错误，作者能不能给一下指导。

**Comment by WenmuZhou** [comment]
这个问题没遇到过呢

**Comment by xbpgithub** [comment]
我把测试部分注释掉，改用每隔几个epoch保存一次模型，程序能完整训练。所以，应该是测试导致了训练的中止。可能是pytorch内部的bug，或者是系统环境的bug，我还没找到问题在哪

**Comment by WenmuZhou** [comment]
找到了告诉一声，我改一下，我这边跑的一直是没有问题的

**Comment by xbpgithub** [comment]
如果不使用多线程加载数据，也就是把workers置为0，则程序能继续训练。也有人提到pytorch数据加载多线程报错的问题，但这里并不报错。所以是线程被一直阻塞了，我不知道该怎么解决

**Comment by WenmuZhou** [comment]
你是win下面跑的吗

**Comment by xbpgithub** [comment]
环境是Ubuntu18.04，RTX2080，cuda10，pytorch1.0，在pycharm edu上跑的
我正打算在Windows上试试呢
我是一个新手，刚开始接触pytorch，还有很多不懂的地方，望不吝赐教。最近在做文本检测这一块，所以对您的这个项目挺赶兴趣的。还有我没有用过C++，您这个项目的C++部分的代码看不太懂，能不能指点一下，用什么写的，需要看哪些东西

**Comment by WenmuZhou** [comment]
我这边ubuntu18.04 1080ti cuda9.2 pytorch1.0是正常的，c++那个代码可能需要你慢慢啃了

**Comment by xbpgithub** [comment]
好的，多谢！
