### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ztoString** [WenmuZhou/PSENet.pytorch#30]
亲爱的老哥，又要麻烦你了，我实在不知道为什么会跑出个这个错误。
是不是我编译pse出问题了，因为之前在训练过程的验证阶段，报错：找不到pse.cpp，所以我就删除了pse文件夹重新编译，当然在编译过程中，还是有错误，比如g++: error: unrecognized command line option ‘-fno-plt’，那么我把-fno-plt直接删去，又报：pse.cpp:1:0: error: bad value (haswell) for -mtune= switch，好吧，我又把-mtune=haswell删去，貌似编译通了，然后再次训练，在验证阶段，就凉了~~~~~
![image](https://user-images.githubusercontent.com/30320878/63772567-ec6e8500-c90b-11e9-9393-ca620e5a3e57.png)

**Comment by ztoString** [comment]
我是直接在这里边替换的：Makefile第一行：
CXXFLAGS = -I include  -std=c++11 -O3 -I/data/zhengjunjun/wangyan02/anaconda3/envs/pytorch/include/python3.6m -I/data/zhengjunjun/wangyan02/anaconda3/envs/pytorch/include/python3.6m  -Wno-unused-result -Wsign-compare -march=nocona -ftree-vectorize -fPIC -fstack-protector-strong -O3 -pipe  -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall
LDFLAGS = $(shell python3-config --ldflags)

**Comment by GuoxingYan** [comment]
你怎么解决的啊，兄弟
