### ISSUE TITLE
关于随机种子的设置

### ISSUE THREAD

**Issue by ztoString** [WenmuZhou/PSENet.pytorch#31]
现在的情况是这样的：
![image](https://user-images.githubusercontent.com/30320878/63911778-0cae5900-ca5e-11e9-8c6e-4223dd3fb4d2.png)
我不知道为什么第一个epoch测试1000张图片需要1h，后边的epoch只需要6min就可以跑完？
在对其他数据集做训练的过程中随机种子还有必要存在吗？
大神，劳烦你了~

**Comment by WenmuZhou** [comment]
可能第一个epoch测试的时候存在io问题。

**Comment by ztoString** [comment]
@WenmuZhou 大神，那设置随机种子会影响我在其他数据集比如mtwi上边训练模型的效果吗，我对这方面不太了解，麻烦你了~

**Comment by WenmuZhou** [comment]
不会

**Comment by ztoString** [comment]
@WenmuZhou 好的，谢谢你，大神，真的帮了我好多忙O(∩_∩)O
