### ISSUE TITLE
Adam+MultiStepLR

### ISSUE THREAD

**Issue by ztoString** [WenmuZhou/PSENet.pytorch#32]
Adam本身不就自带衰减效果吗，现在添加了MultiStepLR，貌似是屏蔽了Adam自带的衰减效果，然后设置几个阈值，达到一个阈值，lr = lr * gamma，可是这样有必要吗，为什么效果会优于Adam自身的衰减效果，查了好多资料也没搞明白个中关系，求大佬明示~

**Comment by WenmuZhou** [comment]
adam 有这个效果吗，我不太懂啊

**Comment by ztoString** [comment]
@WenmuZhou 大神，麻烦问一下，怎么样设置可以使用PSENet-2s呀，是只把config.py文件中的scale设置为2就可以了吗

**Comment by ztoString** [comment]
@WenmuZhou 大神，求救~~~

**Comment by WenmuZhou** [comment]
@ztoString 是的
