### ISSUE TITLE
训练的问题

### ISSUE THREAD

**Issue by matchaqaq** [WenmuZhou/PSENet.pytorch#33]
当用eval函数校验模型时，会报ZIP entry not valid 的问题（Ubuntu18 cuda10 pytorch1.1.0）麻烦帮助解决一下。Thanks♪(･ω･)ﾉ
![image](https://user-images.githubusercontent.com/43446506/64225301-63f47380-cf0d-11e9-8283-9a665198848f.png)

**Comment by FanShuixing** [comment]
@matchaqaq 因为名称不匹配的问题，作者给出的格式需要是gt_1.jpg,在call/script.py中，Line16~17行给出了正则表达式，只需改成符合你数据的格式就行

**Comment by matchaqaq** [comment]
是的，确实是这个问题，多谢大神指点，谢谢！------------------ 原始邮件 ------------------
发件人: "FanShuixing"<notifications@github.com>
发送时间: 2019年9月18日(星期三) 下午2:59
收件人: "WenmuZhou/PSENet.pytorch"<PSENet.pytorch@noreply.github.com>;
抄送: "matchaqaq"<77550430@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [WenmuZhou/PSENet.pytorch] 训练的问题 (#33)



@matchaqaq 因为名称不匹配的问题，作者给出的格式需要是gt_1.jpg,在call/script.py中，Line16~17行给出了正则表达式，只需改成符合你数据的格式就行
 
&mdash;

**Comment by dinhthangbkhn** [comment]
def default_evaluation_params():
    """
    default_evaluation_params: Default parameters to use for the validation and evaluation.
    """
    return {
        'IOU_CONSTRAINT': 0.5,
        'AREA_PRECISION_CONSTRAINT': 0.5,
        'GT_SAMPLE_NAME_2_ID': 'gt_([0-9]+).txt',
        **'DET_SAMPLE_NAME_2_ID': 'res_img_([0-9]+).txt',**
        'LTRB': False,  # LTRB:2points(left,top,right,bottom) or 4 points(x1,y1,x2,y2,x3,y3,x4,y4)
        'CRLF': False,  # Lines are delimited by Windows CRLF format
        'CONFIDENCES': False,  # Detections must include confidence value. AP will be calculated
        'PER_SAMPLE_RESULTS': True  # Generate per sample results and produce data for visualization
    }

I think that you can edit DET_SAMPLE_NAME_2_ID to **res_img_([0-9]+).txt** to fix this problem
