### ISSUE TITLE
Scale 调成4之后出现IndexError

### ISSUE THREAD

**Issue by HikariTJU** [WenmuZhou/PSENet.pytorch#34]
File "/media/data/pse2/models/loss.py", line 86, in ohem_single
    neg_score = score[gt_text <= 0.5]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 160 but corresponding boolean dimension is 640

请问怎么解决？

**Comment by WenmuZhou** [comment]
debug一下

**Comment by HikariTJU** [comment]
> debug一下

虽然我没debug出来，但是还有另一个问题，PSENet1s+Resnet152 batch_size 4 跑了两遍recall都只有60多， 为什么

**Comment by WenmuZhou** [comment]
我最近也遇到了这个问题，我之前可以跑77的现在只能跑68了

**Comment by Whu-wxy** [comment]
scale=4时模型得到的形状是160x160，label是640x640，label没有缩小

**Comment by Whu-wxy** [comment]
在image_label最后加一个这个？
imgs[1] = cv2.resize(imgs[1], dsize=None, fx=1/config.scale, fy=1/config.scale) 
imgs[2] = cv2.resize(imgs[2], dsize=None, fx=1 / config.scale, fy=1 / config.scale)
