### ISSUE TITLE
模型在SCUT-CTW1500数据集上的效果怎么样？

### ISSUE THREAD

**Issue by FanShuixing** [WenmuZhou/PSENet.pytorch#36]
你好，我想请教下这个代码在scut数据集上的效果怎么样，我用这个代码在icdar15数据集上测试过，效果能达到precision:0.8212，recall:0.7694，hmean:0.7944。
有一点不太明白的是论文中提出psenet可以痛过分割检测出任意形状的文字，但是我在看代码中生成mask的时候，是通过边框的四点坐标将原来的边框整个转换为了mask，是否对于scut数据集有不同的处理方式？（或者是大体都是将边框转换为mask的形式）

**Comment by WenmuZhou** [comment]
我这个没有支持弯曲的文本，目前只支持四边形这种，不过弯曲的也是把标注转成mask

**Comment by FanShuixing** [comment]
好的，非常感谢

**Comment by shaohailin** [comment]
@FanShuixing 你测试的scut数据集结果是多少？在icdar15数据集是多少？

**Comment by shaohailin** [comment]
我根据作者在config.py里面设置scale=1,在eval.py中设置scale=4运行的结果
![图片](https://user-images.githubusercontent.com/56865153/70401244-c2c80c80-1a69-11ea-9c14-9cdd96a5440a.png)
效果比你的低很多@FanShuixing ，请问你有没有改过上述scale？
precision:0.8212，recall:0.7694，hmean:0.7944。


我改了一下在config.py里面仍设置scale=1,在eval.py中设置scale=1运行的结果
![图片](https://user-images.githubusercontent.com/56865153/70401259-d1aebf00-1a69-11ea-906d-2f3344bcb89e.png)
我想问一下为什么作者在config.py里面设置scale=1,在eval.py中设置scale=4？
@WenmuZhou

**Comment by WenmuZhou** [comment]
因为eval中设置scale可以在预测的时候提速，降低一点点精度

**Comment by shaohailin** [comment]
1.仅仅在config.py里面仍设置scale=2，是不是对应PSE2s ? 其他地方还需要改动吗？

2.我的测试结果与你的相差很大啊 求指点 如何改进提升一下
![图片](https://user-images.githubusercontent.com/56865153/70583909-23864f00-1bfa-11ea-9294-3cbcb5b2a325.png)

![图片](https://user-images.githubusercontent.com/56865153/70583884-09e50780-1bfa-11ea-9128-fcb9caf4309c.png)
@WenmuZhou
