### ISSUE TITLE
作者你好，想知道你的训练花费了多久？我的loss一直就是1.0

### ISSUE THREAD

**Issue by liuzhuang1024** [WenmuZhou/PSENet.pytorch#37]

**Comment by WenmuZhou** [comment]
一整天

**Comment by liuzhuang1024** [comment]
> 一整天

谢谢回复！还有一个问题是我的loss一直在1.0不变，是因为我没有做负样本的原因吗？可以在readdme中放上loss的图吗？谢谢！

**Comment by WenmuZhou** [comment]
看你的label，框里的文本不能是### 或者*

**Comment by liuzhuang1024** [comment]
> 看你的label，框里的文本不能是### 或者*

![image](https://user-images.githubusercontent.com/23006154/65496960-ffb14800-deeb-11e9-8ba9-69de237cc922.png)




这里已经被我注释掉了


主要是我自己没有做负样本！

**Comment by liuzhuang1024** [comment]
> > 看你的label，框里的文本不能是### 或者*
> 
> ![image](https://user-images.githubusercontent.com/23006154/65496960-ffb14800-deeb-11e9-8ba9-69de237cc922.png)
> 
> 这里已经被我注释掉了
> 
> 主要是我自己没有做负样本！
![image](https://user-images.githubusercontent.com/23006154/65498601-c0382b00-deee-11e9-810a-5a983086dfb9.png)

知道了，样本被我做反了
*********
谢谢作者的回答！

**Comment by WenmuZhou** [comment]
好的
