### ISSUE TITLE
pan.baidu download

### ISSUE THREAD

**Issue by p-tryk** [WenmuZhou/PSENet.pytorch#4]
Please can you make the following files available on onedrive or google drive, it is difficult for non-chinese users to download

resnet50 and resnet152 model on icdar 2015: bauduyun extract code: rxjf

**Comment by WenmuZhou** [comment]
I will update after 2019.5.5





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by WenmuZhou** [comment]
@p-tryk a google drive link has been added to README.me
