### ISSUE TITLE
精度

### ISSUE THREAD

**Issue by donglinAI** [WenmuZhou/PSENet.pytorch#43]
根据链接下载的模型eval的精度分别是77 和 78 ，这是正常的吗，比论文低许多呀！

**Comment by WenmuZhou** [comment]
不正常啊，我当时测的是readme里的精度差不多

**Comment by donglinAI** [comment]
![image](https://user-images.githubusercontent.com/41879987/67255749-3613c000-f4b6-11e9-98da-c469701c840e.png)

我下载的是这里的模型，确实不高。另外想问一下，这个模型只是在预训练模型pre-r50训练icdar2015吗，还是说也经过了2017MLT等数据集的训练，然后在icdar2015上微调了一下。

**Comment by WenmuZhou** [comment]
只用了icd15的数据+imagenet pre
