### ISSUE TITLE
ValueError: num_samples should be a positive integeral value, but got num_samples=0

### ISSUE THREAD

**Issue by Abdulazizbek** [WenmuZhou/PSENet.pytorch#5]
Hello, I tried to run ICD2015 dataset. But get this error:

![image](https://user-images.githubusercontent.com/15800037/57192548-af514200-6f6c-11e9-8262-c52664500c96.png)

OS: Ubuntu 16.04
pytorch 1.0

**Comment by WenmuZhou** [comment]
You can check your dataset, the format of the dataset is the same as icdar15

**Comment by Abdulazizbek** [comment]
@WenmuZhou Yes. I'm using ICD2105 dataset which provided by the official website. Nothing changed

**Comment by WenmuZhou** [comment]
can you upload your dataset?

**Comment by Crescentz** [comment]
The same question? how resloved it

**Comment by Crescentz** [comment]
ignore it ，delate ‘/’ ，all is ok
