### ISSUE TITLE
Pre-Trained Models

### ISSUE THREAD

**Issue by nelaturuharsha** [WenmuZhou/PSENet.pytorch#50]
Hello -- are the weights for the pre-trained models the ones available on the struck out links in the readme -- that of ResNet50 and 152. 

If not -- where could I download them?

Would be really grateful for any help :D 

Thank you!

**Comment by WenmuZhou** [comment]
I won’t update the pre-train model anymore, you can train one yourself if needed

**Comment by nelaturuharsha** [comment]
So I'm assuming the models that are available on the links are indeed the
pre-trained models for your implementation?

Thank you for the quick response.

**Comment by WenmuZhou** [comment]
The model in readme is suit for previous model arch. Now the model arch is updated and it is no longer applicable.

**Comment by nelaturuharsha** [comment]
Thank you for the clarification. Have a great day.
