### ISSUE TITLE
数据预处理

### ISSUE THREAD

**Issue by xxlxx1** [WenmuZhou/PSENet.pytorch#51]
现在这个数据预处理是参考east的，所以剪裁的时候是选择部分纯背景部分含文字且不会从中间切开，作者是都处理成label图像，然后和原图一起随机剪裁变化，如果训练数据含密集文本，用这个方法比较好

**Comment by WenmuZhou** [comment]
理论上east的好一点，但是测下来好像区别不大

**Comment by xxlxx1** [comment]
之前我用增值税发票训练，因为到处都是框又不能从中间切断，所以随机剪裁出来的没什么区别，几乎都是原始图片，达不到数据增强的效果，像场景图片不存在这个问题
