### ISSUE TITLE
Bug (maybe) 需要check 一下: pse.cpp

### ISSUE THREAD

**Issue by jjjjohnson** [WenmuZhou/PSENet.pytorch#56]
pse.cpp 中 的[这行](https://github.com/WenmuZhou/PSENet.pytorch/blob/046f2205a26fb9976d97f8af01036468f94f51a7/pse/pse.cpp#L55) 是从kernel 的 channel 4 到 0 (从第二大的的map, mgerge 到 最小的map. 但是paper 中的后处理是从最小(channel 0) merge 到最大(channel 5)). 根据 [这行](https://github.com/WenmuZhou/PSENet.pytorch/blob/046f2205a26fb9976d97f8af01036468f94f51a7/pse/__init__.py#L24) kernel 的channel 0 是最小的, 同时 [label generation](https://github.com/WenmuZhou/PSENet.pytorch/blob/046f2205a26fb9976d97f8af01036468f94f51a7/dataset/data_utils.py#L130) 也是 从小到大 生成的label的. 所以我认为:[这行](https://github.com/WenmuZhou/PSENet.pytorch/blob/046f2205a26fb9976d97f8af01036468f94f51a7/pse/pse.cpp#L55) 应该改为 : `for (int i = 1; i<c; i++)` 这样才能从倒数第二小merge 到最大.

**Comment by WenmuZhou** [comment]
来个pr吧

**Comment by jjjjohnson** [comment]
pr已经merge
