### ISSUE TITLE
需要重新单独划一部分验证集吗

### ISSUE THREAD

**Issue by NextGuido** [WenmuZhou/PSENet.pytorch#58]
@WenmuZhou 你好，我刚接触psenet，有个小疑问。因为我之前写的代码在训练的时候都会单独划一部分作为验证集以防止过拟合，请问这里是否也需要呢？感谢

**Comment by WenmuZhou** [comment]
需要的

**Comment by NextGuido** [comment]
我看您这里面并没有使用验证集，有试过划分验证集之后测试recall和precision吗？

**Comment by WenmuZhou** [comment]
我只划分了训练集和验证集，没有测试集

**Comment by NextGuido** [comment]
我可以问一下您的另一个项目的问题吗，那个项目没有开issues？困扰了我好久，一直没有解决。麻烦了
