### ISSUE TITLE
解决加载模型，继续训练报错的问题。

### ISSUE THREAD

**Issue by deping-1** [WenmuZhou/PSENet.pytorch#60]
文慕大佬的代码超级棒。

模型训练意外中断，加载模型继续训练报错如下：
KeyError: "param 'initial_lr' is not specified in param_groups[*] when resuming an optimizer"

解决：修改train.py 194行 start_epoch = load_checkpoint(config.checkpoint, model, logger)为 start_epoch = load_checkpoint(config.checkpoint, model, logger, device, optimizer) 添加optimizer参数。

**Comment by WenmuZhou** [comment]
finish
