### ISSUE TITLE
纯文本（非场景）的检测问题

### ISSUE THREAD

**Issue by 471417367** [WenmuZhou/PSENet.pytorch#66]
非常感谢作者的分享，想请教一个问题。
对于纯文本（报告，论文这种），在测试的时候同一行的文字可能因为字与字之间有标点符合或空格导致分出很多框，实际上一行一个框在后续crnn+lstm的时候都是能识别出来的。之所以希望能一个框的就不要多个框，是因为每多一个框就导致crnn+lstm要多处理一张图片，速度太慢。
现在都用开源数据训练，就CTPN一行一个框，EAST和PSENet都偏向出很多框，请问有什么办法调整这种情况吗？

**Comment by 471417367** [comment]
如果自己标了些数据，怎么用现有的模型作预训练模型再训练呢

**Comment by WenmuZhou** [comment]
在这里设置 https://github.com/WenmuZhou/PSENet.pytorch/blob/master/config.py#L33-L34
restart_training =false
checkpoint = model_path
