### ISSUE TITLE
pse compile

### ISSUE THREAD

**Issue by xuweidongkobe** [WenmuZhou/PSENet.pytorch#7]
How can I compile the pse.so in python 3.5?

**Comment by xiiiiiiii** [comment]
> How can I compile the pse.so in python 3.5?

同问，请问你运行成功了吗？

**Comment by WenmuZhou** [comment]
@xuweidongkobe `cd pse` and run `make`

**Comment by xuweidongkobe** [comment]
@WenmuZhou it can only success in python 3.6. I want know how can I compile the pse.so in python 3.5? Thank you!

**Comment by xuweidongkobe** [comment]
> > How can I compile the pse.so in python 3.5?
> 
> 同问，请问你运行成功了吗？

python 3.6下成功。3.5不成功

**Comment by WenmuZhou** [comment]
我这边是ok的呀
![image](https://user-images.githubusercontent.com/12406017/59573424-77015f80-90e5-11e9-92e1-e9744474fed2.png)

**Comment by xuweidongkobe** [comment]
![1560841056(1)](https://user-images.githubusercontent.com/25764883/59659752-70541480-91d9-11e9-9a1a-8fab753b5e76.jpg)
我这边编译能成功，但是在3.5下代码跑不了，具体错误如上图所示，麻烦您看下，谢谢了

**Comment by WenmuZhou** [comment]
提示很明显了呀，pse.so是3.6下编译的，你的解释器却是3.5

**Comment by xuweidongkobe** [comment]
![1560841321(1)](https://user-images.githubusercontent.com/25764883/59660014-13a52980-91da-11e9-9cf4-1e58a3d58744.jpg)
我理解是因为没有找到libpython3.5m.so.1.0，老哥知道怎么改吗？

**Comment by WenmuZhou** [comment]
这个你得百度一下，我也不是很清楚
