### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by ouening** [WenmuZhou/PSENet.pytorch#73]
训练完成test步骤时出现错误:
<pre>Traceback (most recent call last):
  File &quot;/media/gaoya/disk/DeepLearning/PSENet.pytorch/cal_recall/rrc_evaluation_funcs.py&quot;, line 326, in main_evaluation
    evalData = evaluate_method_fn(p[&apos;g&apos;], p[&apos;s&apos;], evalParams)
  File &quot;/media/gaoya/disk/DeepLearning/PSENet.pytorch/cal_recall/script.py&quot;, line 136, in evaluate_method
    subm = rrc_evaluation_funcs.load_folder_file(submFilePath, evaluationParams[&apos;DET_SAMPLE_NAME_2_ID&apos;], True)
  File &quot;/media/gaoya/disk/DeepLearning/PSENet.pytorch/cal_recall/rrc_evaluation_funcs.py&quot;, line 102, in load_folder_file
    raise Exception(&apos;ZIP entry not valid: %s&apos; % name)
Exception: ZIP entry not valid: res_10细挣确数__384.txt
Traceback (most recent call last):
  File &quot;train.py&quot;, line 266, in &lt;module&gt;
    main()
  File &quot;train.py&quot;, line 220, in main
    recall, precision, f1 = eval(model, os.path.join(config.output_dir, &apos;output&apos;), config.testroot, device)
  File &quot;train.py&quot;, line 152, in eval
    return result_dict[&apos;recall&apos;], result_dict[&apos;precision&apos;], result_dict[&apos;hmean&apos;]
TypeError: string indices must be integers
</pre>
查看output输出这个文件是有内容的,请问是什么原因呢?采用自定义的数据集,只需要定位,不需要识别,因为是小语种,数据集示例如下:
40,54,40,171,151,171,151,54,easy
20,197,20,287,152,287,152,197,easy
43,309,43,425,165,425,165,309,easy
52,449,52,545,159,545,159,449,easy
57,562,57,661,160,661,160,562,easy
61,726,61,825,169,825,169,726,easy

**Comment by WenmuZhou** [comment]
10细挣确数__384是你的图片名吗

**Comment by WenmuZhou** [comment]
你看一下这个变量里的内容可能会有帮助evaluationParams

**Comment by ouening** [comment]
请问是在哪个文件呢？没有找到
还有一点疑问就是在文件`data_utils.py`中第200行，为什么是当label为*或者###的时候text_tags为True呢，我看这个是控制生成mask的，即第85行，那应该label不为*或者###时才当作是有效训练信息吧？

**Comment by WenmuZhou** [comment]
File "/media/gaoya/disk/DeepLearning/PSENet.pytorch/cal_recall/script.py",

**Comment by WenmuZhou** [comment]
我这个tag为True就是不用的意思

**Comment by ouening** [comment]
我检查了一下代码,可能是我的数据集不符合命名要求导致的,函数load_folder_file传入的第二个参数是res_img_([0-9]+).txt,按照icdar15的命名应该是img_1.jpg/gt_img_1.txt这样子的,要Img加数字

**Comment by WenmuZhou** [comment]
对的

**Comment by ouening** [comment]
还踩了一个坑,ICDAR15的标注格式是左上角为(x1,y1)起点,==逆时针方向标注==
![image](https://user-images.githubusercontent.com/15122811/80307364-32614d00-87fb-11ea-8a16-9dc6af9ccd85.png)
而在代码中验证坐标方向的时候描述有误,例如以下错误提示:
<pre>File &quot;/media/gaoya/disk/DeepLearning/PSENet.pytorch/cal_recall/rrc_evaluation_funcs.py&quot;, line 281, in validate_clockwise_points
    raise Exception(&quot;Points are not clockwise. The coordinates of bounding quadrilaterals have to be given in clockwise order. Regarding the correct interpretation of &apos;clockwise&apos; remember that the image coordinate system used is the standard one, with the image origin at the upper left, the X axis extending to the right and Y axis extending downwards.&quot;)
Exception: Points are not clockwise. The coordinates of bounding quadrilaterals have to be given in clockwise order. Regarding the correct interpretation of &apos;clockwise&apos; remember that the image coordinate system used is the standard one, with the image origin at the upper left, the X axis extending to the right and Y axis extending downwards.
</pre>
网上搜了以下关于ICDAR数据集的描述好像都有问题,以ICDAR5的gt_img_1.txt中的第一条标注为例进行可视化:
377,117,463,117,465,130,378,130,Genaxis Theatre
```python
import matplotlib.pyplot as plt
import numpy as np

x = [377,463,465,378]
y = [117,117,130,130]

plt.plot(x,y)
plt.scatter(x,y)
string = ['a','b','c','d']
for x_,y_,s in zip(x,y,string):
    plt.text(x_,y_,s,fontsize=15)

plt.show()
```
得到以下结果:
![image](https://user-images.githubusercontent.com/15122811/80307636-e1eaef00-87fc-11ea-993b-d3e6cffc93e7.png)
起始点应该是左下角为(x1,y1),逆时针顺序
